//Create a C++ program that uses a `for` loop to simulate a guessing game. Generate a random number between 1 and 100
//, and have the user guess the number. Provide hints if the guess is too high or too low until they guess correctly.
#include <iostream>
using namespace std;

int main() {
    srand(time(NULL));          // makes the randomization to work by feeding in the random number generator a seed
    int x = rand() % 100 + 1;  // a random number that can be any integer (maybe very large) is generated by rand() function
    cout << x << endl; 
    int num;
    for (int i = 1; i <= num; i++) {
        cin >> num;
        if (num < x) {
                cout << "To Low " << endl;
            
            } else if (num > x) {
                cout << "To high " << endl;
            
            }
         if (num==x) {
            cout << "Great you got it!";
            break;
        }
    }
}